server:
  port: 8083
  servlet:
    context-path: /auth

spring:
  application:
    name: auth
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3308/auth
    username: user
    password: password

security:
  jwt:
    token:
      secret-key: A3gm89d04msadsYFEWK87032gbHGDJ1FHF
      time-expire: 360000

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/registry/eureka
